# Generated by Django 5.0.6 on 2025-01-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lostitem_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('found_item_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_found', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='found_items/')),
            ],
            options={
                'verbose_name': 'Found Item',
                'verbose_name_plural': 'Found Items',
            },
        ),
    ]
